sudo: required
services:
  - docker

env:
  - DJANGO_VERSION=2.0
  - DJANGO_SETTINGS_MODULE='backend.config.settings.local'

before_install:
  - docker build -t ktryber/vue-test -f ./frontend/dev.Dockerfile ./frontend
  - docker build -t ktryber/django-test -f ./backend/dev.Dockerfile ./backend

script:
  - docker run ktryber/vue-test npm run test
  - docker run ktryber/django-test python manage.py test

after_success:
  - docker build -t ktryber/django-vue-docker-frontend ./frontend
  - docker build -t ktryber/django-vue-docker-backend ./backend
  - docker build -t ktryber/django-vue-docker-nginx ./nginx
  # Add your docker login to travis environment variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push ktryber/django-vue-docker-frontend
  - docker push ktryber/django-vue-docker-backend
  - docker push ktryber/django-vue-docker-nginx
