version: "3"

services:
  db:
    image: postgres
  api:
    build:
      dockerfile: dev.Dockerfile
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    command: npm run serve
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "8080:8080"
