version: "3"

services:
  db:
    image: "postgres:latest"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    env_file: ./backend/secrets/.env
  client:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
