version: "3"

services:
  db:
    image: postgres
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    volumes:
      - ./backend/staticfiles/:/staticfiles/
  api:
    build:
      dockerfile: dev.Dockerfile
      context: ./backend
    command: /entrypoint.sh
    volumes:
      - ./backend:/app
    depends_on:
      - db
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
