version: "3"

services:
  db:
    image: postgres
  nginx:
    depends_on:
      - client
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    volumes:
      - ./backend/config/staticfiles/:/staticfiles/
  api:
    build:
      dockerfile: dev.Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file: ./backend/secrets/.env
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
