version: "3"

services:
  db:
    restart: always
    image: postgres
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    volumes:
      - ./backend/config/staticfiles/:/staticfiles/
  api:
    build:
      dockerfile: dev.Dockerfile
      context: ./backend
    command: /entrypoint.sh
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file: ./backend/secrets/.env
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres_password
      - PG_HOST=db
      - PG_NAME=postgres
      - PG_PORT=5432
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    command: npm run serve
    volumes:
      - /app/node_modules
      - ./frontend:/app
