version: "3"

services:
  db:
    image: postgres
  nginx:
    depends_on:
      - client
      - api
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: dev.Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file: ./backend/secrets/.env
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
