version: "3"

services:
  db:
    image: "postgres:latest"
  nginx:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: dev.Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/app/staticfiles/
    env_file: ./backend/secrets/.env
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
