version: "3"

services:
  db:
    image: postgres
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    volumes:
      - ./backend/staticfiles/:/staticfiles/
  api:
    build:
      dockerfile: dev.Dockerfile
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    command: npm run serve
    volumes:
      - /app/node_modules
      - ./frontend:/app
