FROM node:10-alpine as build

WORKDIR /app/

COPY frontend/package.json frontend/package-lock.json /app/

RUN npm install

COPY frontend /app/

COPY .env /app/.env

RUN npm run build

FROM nginx:alpine

COPY nginx/prod.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/ /dist/

CMD ["nginx", "-g", "daemon off;"]
